FROM node:18-alpine AS builder

WORKDIR /app

COPY backend_service/package*.json ./
RUN npm ci

COPY backend_service/ .

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

CMD ["node", "dist/main"]
